// Approximations of the CSS variables VS Code gives webviews, for rendering outside VS Code.
// Not exact theme dumps: enough to judge contrast, surfaces and theme integration.

export type ThemeName = "light" | "dark" | "hc";

export const BODY_CLASS: Record<ThemeName, string> = { light: "vscode-light", dark: "vscode-dark", hc: "vscode-high-contrast" };

const common = "--vscode-font-family:'Segoe UI',system-ui,sans-serif;--vscode-font-size:13px;--vscode-editor-font-family:Consolas,'Courier New',monospace;--vscode-editor-font-size:12px";

export const THEMES: Record<ThemeName, string> = {
  // Light Modern
  light: `${common};--vscode-foreground:#3b3b3b;--vscode-descriptionForeground:#717171;--vscode-disabledForeground:rgba(97,97,97,.5);--vscode-editor-background:#ffffff;--vscode-editor-foreground:#3b3b3b;--vscode-sideBar-background:#f8f8f8;--vscode-sideBar-border:#e5e5e5;--vscode-panel-border:#e5e5e5;--vscode-editorWidget-background:#f8f8f8;--vscode-widget-border:#e5e5e5;--vscode-widget-shadow:rgba(0,0,0,.16);--vscode-list-hoverBackground:#f2f2f2;--vscode-list-inactiveSelectionBackground:#e4e6f1;--vscode-list-activeSelectionBackground:#e8e8e8;--vscode-list-activeSelectionForeground:#000000;--vscode-toolbar-hoverBackground:rgba(184,184,184,.31);--vscode-textLink-foreground:#005fb8;--vscode-input-background:#ffffff;--vscode-input-border:#cecece;--vscode-input-foreground:#3b3b3b;--vscode-input-placeholderForeground:#767676;--vscode-focusBorder:#005fb8;--vscode-button-background:#005fb8;--vscode-button-hoverBackground:#0258a8;--vscode-button-foreground:#ffffff;--vscode-button-secondaryBackground:#e5e5e5;--vscode-button-secondaryForeground:#3b3b3b;--vscode-textCodeBlock-background:#f8f8f8;--vscode-textPreformat-background:rgba(0,0,0,.06);--vscode-textPreformat-foreground:#3b3b3b;--vscode-textBlockQuote-background:#f8f8f8;--vscode-textBlockQuote-border:#e5e5e5;--vscode-badge-background:#cccedb;--vscode-badge-foreground:#3b3b3b;--vscode-activityBarBadge-background:#005fb8;--vscode-activityBarBadge-foreground:#ffffff;--vscode-menu-background:#ffffff;--vscode-menu-selectionBackground:#005fb8;--vscode-menu-selectionForeground:#ffffff;--vscode-testing-iconPassed:#388a34;--vscode-testing-iconFailed:#f14c4c;--vscode-errorForeground:#f85149;--vscode-editorWarning-foreground:#bf8803;--vscode-progressBar-background:#005fb8;--vscode-scrollbarSlider-background:rgba(100,100,100,.4);--vscode-editorIndentGuide-background1:#d3d3d3;--vscode-charts-green:#388a34;--vscode-charts-blue:#1a85ff;--vscode-charts-purple:#652d90;--vscode-charts-orange:#d18616;--vscode-charts-yellow:#bf8803`,
  // Dark Modern
  dark: `${common};--vscode-foreground:#cccccc;--vscode-descriptionForeground:#9d9d9d;--vscode-disabledForeground:rgba(204,204,204,.5);--vscode-editor-background:#1f1f1f;--vscode-editor-foreground:#cccccc;--vscode-sideBar-background:#181818;--vscode-sideBar-border:#2b2b2b;--vscode-panel-border:#2b2b2b;--vscode-editorWidget-background:#202020;--vscode-widget-border:#313131;--vscode-widget-shadow:rgba(0,0,0,.36);--vscode-list-hoverBackground:#2a2d2e;--vscode-list-inactiveSelectionBackground:#37373d;--vscode-list-activeSelectionBackground:#04395e;--vscode-list-activeSelectionForeground:#ffffff;--vscode-toolbar-hoverBackground:rgba(90,93,94,.31);--vscode-textLink-foreground:#4daafc;--vscode-input-background:#313131;--vscode-input-border:#3c3c3c;--vscode-input-foreground:#cccccc;--vscode-input-placeholderForeground:#989898;--vscode-focusBorder:#0078d4;--vscode-button-background:#0078d4;--vscode-button-hoverBackground:#026ec1;--vscode-button-foreground:#ffffff;--vscode-button-secondaryBackground:#313131;--vscode-button-secondaryForeground:#cccccc;--vscode-textCodeBlock-background:#2b2b2b;--vscode-textPreformat-background:#3c3c3c;--vscode-textPreformat-foreground:#d0d0d0;--vscode-textBlockQuote-background:#2b2b2b;--vscode-textBlockQuote-border:#616161;--vscode-badge-background:#616161;--vscode-badge-foreground:#f8f8f8;--vscode-activityBarBadge-background:#0078d4;--vscode-activityBarBadge-foreground:#ffffff;--vscode-menu-background:#1f1f1f;--vscode-menu-selectionBackground:#0078d4;--vscode-menu-selectionForeground:#ffffff;--vscode-testing-iconPassed:#73c991;--vscode-testing-iconFailed:#f14c4c;--vscode-errorForeground:#f85149;--vscode-editorWarning-foreground:#cca700;--vscode-progressBar-background:#0078d4;--vscode-scrollbarSlider-background:rgba(121,121,121,.4);--vscode-editorIndentGuide-background1:#404040;--vscode-charts-green:#89d185;--vscode-charts-blue:#3794ff;--vscode-charts-purple:#b180d7;--vscode-charts-orange:#d18616;--vscode-charts-yellow:#cca700`,
  // High Contrast (dark): black surfaces, contrast borders carry the structure
  hc: `${common};--vscode-foreground:#ffffff;--vscode-descriptionForeground:#ffffffb3;--vscode-disabledForeground:#a5a5a5;--vscode-editor-background:#000000;--vscode-editor-foreground:#ffffff;--vscode-sideBar-background:#000000;--vscode-sideBar-border:#6fc3df;--vscode-panel-border:#6fc3df;--vscode-contrastBorder:#6fc3df;--vscode-contrastActiveBorder:#f38518;--vscode-editorWidget-background:#0c141f;--vscode-widget-border:#6fc3df;--vscode-widget-shadow:transparent;--vscode-list-hoverBackground:transparent;--vscode-list-inactiveSelectionBackground:transparent;--vscode-list-activeSelectionBackground:transparent;--vscode-toolbar-hoverBackground:transparent;--vscode-textLink-foreground:#21a6ff;--vscode-input-background:#000000;--vscode-input-border:#6fc3df;--vscode-input-foreground:#ffffff;--vscode-input-placeholderForeground:#ffffffb3;--vscode-focusBorder:#f38518;--vscode-button-background:#000000;--vscode-button-foreground:#ffffff;--vscode-button-secondaryBackground:#000000;--vscode-button-secondaryForeground:#ffffff;--vscode-textCodeBlock-background:#000000;--vscode-textPreformat-foreground:#ffffff;--vscode-textBlockQuote-border:#ffffff;--vscode-badge-background:#000000;--vscode-badge-foreground:#ffffff;--vscode-activityBarBadge-background:#000000;--vscode-activityBarBadge-foreground:#ffffff;--vscode-menu-background:#000000;--vscode-menu-selectionBackground:transparent;--vscode-testing-iconPassed:#73c991;--vscode-testing-iconFailed:#f48771;--vscode-errorForeground:#f48771;--vscode-editorWarning-foreground:#fff700;--vscode-progressBar-background:#6fc3df;--vscode-scrollbarSlider-background:rgba(111,195,223,.6);--vscode-editorIndentGuide-background1:#ffffff;--vscode-charts-green:#89d185;--vscode-charts-blue:#3794ff;--vscode-charts-purple:#b180d7;--vscode-charts-orange:#d18616;--vscode-charts-yellow:#cca700`
};

/** VS Code injects this into every webview; it switches Chromium to native scrollbars (with arrows) unless overridden. */
// VS Code's default webview styles (src/vs/workbench/contrib/webview/browser/pre/index.html): note the 20px body padding
// and the scrollbar rules, which pages must override themselves.
export const VSCODE_INJECTED_CSS = "html{scrollbar-color:var(--vscode-scrollbarSlider-background) var(--vscode-editor-background)}"
  + "body{background-color:transparent;color:var(--vscode-editor-foreground);font-family:var(--vscode-font-family);font-size:var(--vscode-font-size);margin:0;padding:0 20px}"
  + "img,video{max-width:100%;max-height:100%}a,a code{color:var(--vscode-textLink-foreground)}"
  + "code{font-family:var(--monaco-monospace-font);color:var(--vscode-textPreformat-foreground);background-color:var(--vscode-textPreformat-background);padding:1px 3px;border-radius:4px}pre code{padding:0}"
  + "::-webkit-scrollbar{width:10px;height:10px}::-webkit-scrollbar-corner{background-color:var(--vscode-editor-background)}"
  + "::-webkit-scrollbar-thumb{background-color:var(--vscode-scrollbarSlider-background)}::-webkit-scrollbar-thumb:hover{background-color:var(--vscode-scrollbarSlider-hoverBackground)}::-webkit-scrollbar-thumb:active{background-color:var(--vscode-scrollbarSlider-activeBackground)}";

/** Surfaces script errors and a DOM summary as attributes that `shoot.ts --dump` prints. */
export const ERROR_PROBE = `<script>addEventListener("error",e=>{const d=document.documentElement;d.dataset.err=(d.dataset.err||"")+" | "+e.message+" @"+e.lineno;});</script>`;

export function parseThemes(value: string | undefined): ThemeName[] {
  const names = (value ?? "light,dark").split(",").map(name => name.trim()).filter(Boolean) as ThemeName[];
  for (const name of names) if (!THEMES[name]) throw new Error(`Unknown theme '${name}'. Use light, dark, hc.`);
  return names;
}
